// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cohlnbgvemackoprlfqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaGxuYmd2ZW1hY2tvcHJsZnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDY3MjEsImV4cCI6MjA1NTc4MjcyMX0.WgMQGHfaVo2m3EFnfU28YULFB0Athbg8RykuTmMejt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);